spring:
   datasource:
      username: boardgame_lms
      password: boardgame_lms
      url: jdbc:mysql://localhost:3306/boardgame_lms
      
   jpa:
      hibernate:
         ddl-auto: none
      show-sql: true
      
   sql:
      init:
         mode: never
         
         