INSERT INTO category (category_name) VALUES ('Abstract Strategy');
INSERT INTO category (category_name) VALUES ('Action / Dexterity');
INSERT INTO category (category_name) VALUES ('Adventure');
INSERT INTO category (category_name) VALUES ('Age of Reason');
INSERT INTO category (category_name) VALUES ('American Civil War');
INSERT INTO category (category_name) VALUES ('American Indian Wars');
INSERT INTO category (category_name) VALUES ('American Revolutionary War');
INSERT INTO category (category_name) VALUES ('American West');
INSERT INTO category (category_name) VALUES ('Ancient');
INSERT INTO category (category_name) VALUES ('Animals');
INSERT INTO category (category_name) VALUES ('Arabian');
INSERT INTO category (category_name) VALUES ('Aviation / Flight');
INSERT INTO category (category_name) VALUES ('Bluffing');
INSERT INTO category (category_name) VALUES ('Book');
INSERT INTO category (category_name) VALUES ('Card Game');
INSERT INTO category (category_name) VALUES ('Childrens Game');
INSERT INTO category (category_name) VALUES ('City Building');
INSERT INTO category (category_name) VALUES ('Civil War');
INSERT INTO category (category_name) VALUES ('Civilization');
INSERT INTO category (category_name) VALUES ('Collectible Components');
INSERT INTO category (category_name) VALUES ('Comic Book / Strip');
INSERT INTO category (category_name) VALUES ('Deduction');
INSERT INTO category (category_name) VALUES ('Dice');
INSERT INTO category (category_name) VALUES ('Economic');
INSERT INTO category (category_name) VALUES ('Educational');
INSERT INTO category (category_name) VALUES ('Electronic');
INSERT INTO category (category_name) VALUES ('Environmental');
INSERT INTO category (category_name) VALUES ('Expansion for Base-game');
INSERT INTO category (category_name) VALUES ('Exploration');
INSERT INTO category (category_name) VALUES ('Fan Expansion');
INSERT INTO category (category_name) VALUES ('Fantasy');
INSERT INTO category (category_name) VALUES ('Farming');
INSERT INTO category (category_name) VALUES ('Fighting');
INSERT INTO category (category_name) VALUES ('Game System');
INSERT INTO category (category_name) VALUES ('Horror');
INSERT INTO category (category_name) VALUES ('Humor');
INSERT INTO category (category_name) VALUES ('Industry / Manufacturing');
INSERT INTO category (category_name) VALUES ('Korean War');
INSERT INTO category (category_name) VALUES ('Mafia');
INSERT INTO category (category_name) VALUES ('Math');
INSERT INTO category (category_name) VALUES ('Mature / Adult');
INSERT INTO category (category_name) VALUES ('Maze');
INSERT INTO category (category_name) VALUES ('Medical');
INSERT INTO category (category_name) VALUES ('Medieval');
INSERT INTO category (category_name) VALUES ('Memory');
INSERT INTO category (category_name) VALUES ('Miniatures');
INSERT INTO category (category_name) VALUES ('Modern Warfare');
INSERT INTO category (category_name) VALUES ('Movies / TV / Radio theme');
INSERT INTO category (category_name) VALUES ('Murder/Mystery');
INSERT INTO category (category_name) VALUES ('Music');
INSERT INTO category (category_name) VALUES ('Mythology');
INSERT INTO category (category_name) VALUES ('Napoleonic');
INSERT INTO category (category_name) VALUES ('Nautical');
INSERT INTO category (category_name) VALUES ('Negotiation');
INSERT INTO category (category_name) VALUES ('Novel-based');
INSERT INTO category (category_name) VALUES ('Number');
INSERT INTO category (category_name) VALUES ('Party Game');
INSERT INTO category (category_name) VALUES ('Pike and Shot');
INSERT INTO category (category_name) VALUES ('Pirates');
INSERT INTO category (category_name) VALUES ('Political');
INSERT INTO category (category_name) VALUES ('Post-Napoleonic');
INSERT INTO category (category_name) VALUES ('Prehistoric');
INSERT INTO category (category_name) VALUES ('Print & Play');
INSERT INTO category (category_name) VALUES ('Puzzle');
INSERT INTO category (category_name) VALUES ('Racing');
INSERT INTO category (category_name) VALUES ('Real-time');
INSERT INTO category (category_name) VALUES ('Religious');
INSERT INTO category (category_name) VALUES ('Renaissance');
INSERT INTO category (category_name) VALUES ('Science Fiction');
INSERT INTO category (category_name) VALUES ('Space Exploration');
INSERT INTO category (category_name) VALUES ('Spies/Secret Agents');
INSERT INTO category (category_name) VALUES ('Sports');
INSERT INTO category (category_name) VALUES ('Territory Building');
INSERT INTO category (category_name) VALUES ('Trains');
INSERT INTO category (category_name) VALUES ('Transportation');
INSERT INTO category (category_name) VALUES ('Travel');
INSERT INTO category (category_name) VALUES ('Trivia');
INSERT INTO category (category_name) VALUES ('Video Game Theme');
INSERT INTO category (category_name) VALUES ('Vietnam War');
INSERT INTO category (category_name) VALUES ('Wargame');
INSERT INTO category (category_name) VALUES ('Word Game');
INSERT INTO category (category_name) VALUES ('World War I');
INSERT INTO category (category_name) VALUES ('World War II');
INSERT INTO category (category_name) VALUES ('Zombies');

INSERT INTO designer (first_name, last_name) VALUES ('Uwe', 'Rosenberg');
INSERT INTO designer (first_name, last_name) VALUES ('Reiner', 'Knizia');
INSERT INTO designer (first_name, last_name) VALUES ('Corey', 'Konieczka');
INSERT INTO designer (first_name, last_name) VALUES ('Stefan', 'Feld');
INSERT INTO designer (first_name, last_name) VALUES ('Bruno', 'Cathala');
INSERT INTO designer (first_name, last_name) VALUES ('Eric M.', 'Lang');
INSERT INTO designer (first_name, last_name) VALUES ('Vlaada', 'Chvátil');
INSERT INTO designer (first_name, last_name) VALUES ('Simone', 'Luciani');
INSERT INTO designer (first_name, last_name) VALUES ('Wolfgang', 'Kramer');
INSERT INTO designer (first_name, last_name) VALUES ('Vital', 'Lacerda');
INSERT INTO designer (first_name, last_name) VALUES ('Martin', 'Wallace');
INSERT INTO designer (first_name, last_name) VALUES ('Alexander', 'Pfister');
INSERT INTO designer (first_name, last_name) VALUES ('Michael', 'Kiesling');
INSERT INTO designer (first_name, last_name) VALUES ('Shem', 'Phillips');
INSERT INTO designer (first_name, last_name) VALUES ('Jamey', 'Stegmaier');
INSERT INTO designer (first_name, last_name) VALUES ('Daniele', 'Tascini');
INSERT INTO designer (first_name, last_name) VALUES ('Antoine', 'Bauza');
INSERT INTO designer (first_name, last_name) VALUES ('Wolfgang', 'Warsch');
INSERT INTO designer (first_name, last_name) VALUES ('Richard', 'Garfield');
INSERT INTO designer (first_name, last_name) VALUES ('Jeroen', 'Doumen');
INSERT INTO designer (first_name, last_name) VALUES ('Thomas', 'Lehmann');
INSERT INTO designer (first_name, last_name) VALUES ('Ignacy', 'Trzewiczek');
INSERT INTO designer (first_name, last_name) VALUES ('Christian T.', 'Petersen');
INSERT INTO designer (first_name, last_name) VALUES ('Rüdiger', 'Dorn');
INSERT INTO designer (first_name, last_name) VALUES ('Virginio', 'Gigli');
INSERT INTO designer (first_name, last_name) VALUES ('Vladimír', 'Suchý');
INSERT INTO designer (first_name, last_name) VALUES ('Phil', 'Walker-Harding');
INSERT INTO designer (first_name, last_name) VALUES ('Richard', 'Borg');
INSERT INTO designer (first_name, last_name) VALUES ('Matthias', 'Cramer');
INSERT INTO designer (first_name, last_name) VALUES ('Mac', 'Gerdts');
INSERT INTO designer (first_name, last_name) VALUES ('Ryan', 'Laukat');
INSERT INTO designer (first_name, last_name) VALUES ('Inka', 'Brand');
INSERT INTO designer (first_name, last_name) VALUES ('Cole', 'Wehrle');
INSERT INTO designer (first_name, last_name) VALUES ('Jason', 'Matthews');
INSERT INTO designer (first_name, last_name) VALUES ('Flaminia', 'Brasini');
INSERT INTO designer (first_name, last_name) VALUES ('Paolo', 'Mori');
INSERT INTO designer (first_name, last_name) VALUES ('Jens', 'Drögemüller');
INSERT INTO designer (first_name, last_name) VALUES ('Xavier', 'Georges');
INSERT INTO designer (first_name, last_name) VALUES ('Friedemann', 'Friese');
INSERT INTO designer (first_name, last_name) VALUES ('Richard', 'Amann');
INSERT INTO designer (first_name, last_name) VALUES ('Chad', 'Jensen');
INSERT INTO designer (first_name, last_name) VALUES ('Matt', 'Leacock');
INSERT INTO designer (first_name, last_name) VALUES ('Ted', 'Alspach');
INSERT INTO designer (first_name, last_name) VALUES ('Andreas', 'Seyfarth');
INSERT INTO designer (first_name, last_name) VALUES ('Paul', 'Dennen');
INSERT INTO designer (first_name, last_name) VALUES ('Dávid', 'Turczi');
INSERT INTO designer (first_name, last_name) VALUES ('Jonathan', 'Gilmour-Long');
INSERT INTO designer (first_name, last_name) VALUES ('Kris', 'Burm');
INSERT INTO designer (first_name, last_name) VALUES ('Bruno', 'Faidutti');
INSERT INTO designer (first_name, last_name) VALUES ('Ludovic', 'Roudy');
INSERT INTO designer (first_name, last_name) VALUES ('Sébastien', 'Dujardin');
INSERT INTO designer (first_name, last_name) VALUES ('Bernd', 'Brunnhofer');
INSERT INTO designer (first_name, last_name) VALUES ('Alan R.', 'Moon');
INSERT INTO designer (first_name, last_name) VALUES ('Glenn', 'Drover');
INSERT INTO designer (first_name, last_name) VALUES ('Andreas', 'Steding');
INSERT INTO designer (first_name, last_name) VALUES ('Reiner', 'Stockhausen');
INSERT INTO designer (first_name, last_name) VALUES ('Sébastien', 'Pauchon');
INSERT INTO designer (first_name, last_name) VALUES ('Carl', 'Chudyk');
INSERT INTO designer (first_name, last_name) VALUES ('Dirk', 'Henn');
INSERT INTO designer (first_name, last_name) VALUES ('Bill', 'Eberle');
INSERT INTO designer (first_name, last_name) VALUES ('Richard', 'Breese');
INSERT INTO designer (first_name, last_name) VALUES ('Jay', 'Little');
INSERT INTO designer (first_name, last_name) VALUES ('Régis', 'Bonnessée');
INSERT INTO designer (first_name, last_name) VALUES ('Helmut', 'Ohley');
INSERT INTO designer (first_name, last_name) VALUES ('Roberto', 'Di Meglio');
INSERT INTO designer (first_name, last_name) VALUES ('Adam', 'Carlson');
INSERT INTO designer (first_name, last_name) VALUES ('Sean', 'Sweigart');
INSERT INTO designer (first_name, last_name) VALUES ('Michael', 'Rieneck');
INSERT INTO designer (first_name, last_name) VALUES ('William', 'Attia');
INSERT INTO designer (first_name, last_name) VALUES ('Mike', 'Elliott');
INSERT INTO designer (first_name, last_name) VALUES ('Dominic', 'Crapuchettes');
INSERT INTO designer (first_name, last_name) VALUES ('Francis', 'Tresham');
INSERT INTO designer (first_name, last_name) VALUES ('Donald X.', 'Vaccarino');
INSERT INTO designer (first_name, last_name) VALUES ('Hisashi', 'Hayashi');
INSERT INTO designer (first_name, last_name) VALUES ('Elizabeth', 'Hargrave');
INSERT INTO designer (first_name, last_name) VALUES ('Sebastian', 'Bleasdale');
INSERT INTO designer (first_name, last_name) VALUES ('Paulo', 'Soledade');
INSERT INTO designer (first_name, last_name) VALUES ('Isaac', 'Childres');
INSERT INTO designer (first_name, last_name) VALUES ('Touko', 'Tahkokallio');
INSERT INTO designer (first_name, last_name) VALUES ('Klaus-Jürgen', 'Wrede');
INSERT INTO designer (first_name, last_name) VALUES ('Jacob', 'Fryxelius');
INSERT INTO designer (first_name, last_name) VALUES ('R. Eric', 'Reuss');
INSERT INTO designer (first_name, last_name) VALUES ('Juma', 'Al-JouJou');
INSERT INTO designer (first_name, last_name) VALUES ('Jacques', 'Bariot');
INSERT INTO designer (first_name, last_name) VALUES ('D. Brad', 'Talton, Jr.');
INSERT INTO designer (first_name, last_name) VALUES ('Jay', 'Cormier');
INSERT INTO designer (first_name, last_name) VALUES ('Richard', 'Sivél');
INSERT INTO designer (first_name, last_name) VALUES ('Ole', 'Steiness');
INSERT INTO designer (first_name, last_name) VALUES ('Sid', 'Sackson');
INSERT INTO designer (first_name, last_name) VALUES ('Michael', 'Keller (II)');
INSERT INTO designer (first_name, last_name) VALUES ('Cédrick', 'Chaboussit');
INSERT INTO designer (first_name, last_name) VALUES ('Christophe', 'Boelinger');
INSERT INTO designer (first_name, last_name) VALUES ('Michael', 'Schacht');
INSERT INTO designer (first_name, last_name) VALUES ('Philippe', 'Keyaerts');
INSERT INTO designer (first_name, last_name) VALUES ('Phil', 'Eklund');
INSERT INTO designer (first_name, last_name) VALUES ('Karl-Heinz', 'Schmiel');
INSERT INTO designer (first_name, last_name) VALUES ('Mark', 'Simonitch');
INSERT INTO designer (first_name, last_name) VALUES ('Mike', 'Fitzgerald');
INSERT INTO designer (first_name, last_name) VALUES ('Dennis K.', 'Chan');
INSERT INTO designer (first_name, last_name) VALUES ('Vangelis', 'Bagiartakis');
INSERT INTO designer (first_name, last_name) VALUES ('Colby', 'Dauch');
INSERT INTO designer (first_name, last_name) VALUES ('Klaus', 'Teuber');
INSERT INTO designer (first_name, last_name) VALUES ('Steve', 'Finn');
INSERT INTO designer (first_name, last_name) VALUES ('John', 'Bohrer');
INSERT INTO designer (first_name, last_name) VALUES ('Stefania', 'Niccolini');
INSERT INTO designer (first_name, last_name) VALUES ('Shadi', 'Torbey');
INSERT INTO designer (first_name, last_name) VALUES ('Günter', 'Cornett');
INSERT INTO designer (first_name, last_name) VALUES ('Leo', 'Colovini');
INSERT INTO designer (first_name, last_name) VALUES ('Bowen', 'Simmons');
INSERT INTO designer (first_name, last_name) VALUES ('Alex', 'Randolph');
INSERT INTO designer (first_name, last_name) VALUES ('Richard', 'Hamblen');
INSERT INTO designer (first_name, last_name) VALUES ('David', 'Sirlin');
INSERT INTO designer (first_name, last_name) VALUES ('Toshiki', 'Sato');

INSERT INTO artist (first_name, last_name) VALUES ('Vincent', 'Dutrait');
INSERT INTO artist (first_name, last_name) VALUES ('Andrew', 'Bosley');
INSERT INTO artist (first_name, last_name) VALUES ('Michael', 'Menzel');
INSERT INTO artist (first_name, last_name) VALUES ('Beth', 'Sobel');
INSERT INTO artist (first_name, last_name) VALUES ('Klemens', 'Franz');
INSERT INTO artist (first_name, last_name) VALUES ('Ian', 'OToole');
INSERT INTO artist (first_name, last_name) VALUES ('Sabrina', 'Miramon');
INSERT INTO artist (first_name, last_name) VALUES ('Dennis', 'Lohausen');
INSERT INTO artist (first_name, last_name) VALUES ('Agnieszka', 'Dabrowiecka');
INSERT INTO artist (first_name, last_name) VALUES ('Lina', 'Cossette');
INSERT INTO artist (first_name, last_name) VALUES ('Natalia', 'Rojas');
INSERT INTO artist (first_name, last_name) VALUES ('Kwanchai', 'Moriya');
INSERT INTO artist (first_name, last_name) VALUES ('Sarah', 'Keele');
INSERT INTO artist (first_name, last_name) VALUES ('Nick', 'Nazzaro');
INSERT INTO artist (first_name, last_name) VALUES ('Ryan', 'Laukat');
INSERT INTO artist (first_name, last_name) VALUES ('Chris', 'Quilliams');
INSERT INTO artist (first_name, last_name) VALUES ('Kyle', 'Ferrin');
INSERT INTO artist (first_name, last_name) VALUES ('Paul K.', 'Halkyon');
INSERT INTO artist (first_name, last_name) VALUES ('Oliver', 'Barrett');
INSERT INTO artist (first_name, last_name) VALUES ('Xavier Gueniffey', 'Durin');
INSERT INTO artist (first_name, last_name) VALUES ('Marie', 'Cardouat');
INSERT INTO artist (first_name, last_name) VALUES ('Ryan', 'Goldsberry');
INSERT INTO artist (first_name, last_name) VALUES ('Manny', 'Tremblay');
INSERT INTO artist (first_name, last_name) VALUES ('Fábio', 'Fontes');
INSERT INTO artist (first_name, last_name) VALUES ('Weberson', 'Santiago');

INSERT INTO publisher (publisher_name) VALUES ('Amarillo Design Bureau');
INSERT INTO publisher (publisher_name) VALUES ('Amigo Spiele');
INSERT INTO publisher (publisher_name) VALUES ('Asmodee');
INSERT INTO publisher (publisher_name) VALUES ('Atlas Games');
INSERT INTO publisher (publisher_name) VALUES ('Australian Design Group');
INSERT INTO publisher (publisher_name) VALUES ('Avalanche Press');
INSERT INTO publisher (publisher_name) VALUES ('Avalon Hill');
INSERT INTO publisher (publisher_name) VALUES ('Battleline Publications');
INSERT INTO publisher (publisher_name) VALUES ('Bestime');
INSERT INTO publisher (publisher_name) VALUES ('Bézier Games');
INSERT INTO publisher (publisher_name) VALUES ('Blue Orange Games');
INSERT INTO publisher (publisher_name) VALUES ('Buffalo Games');
INSERT INTO publisher (publisher_name) VALUES ('Cheapass Games');
INSERT INTO publisher (publisher_name) VALUES ('Chieftain Products');
INSERT INTO publisher (publisher_name) VALUES ('CMON Limited');
INSERT INTO publisher (publisher_name) VALUES ('Columbia Games');
INSERT INTO publisher (publisher_name) VALUES ('Cranium, Inc.');
INSERT INTO publisher (publisher_name) VALUES ('Cryptozoic Entertainment');
INSERT INTO publisher (publisher_name) VALUES ('Czech Games Edition');
INSERT INTO publisher (publisher_name) VALUES ('Darrington Press');
INSERT INTO publisher (publisher_name) VALUES ('Days of Wonder');
INSERT INTO publisher (publisher_name) VALUES ('Decision Games');
INSERT INTO publisher (publisher_name) VALUES ('Drumond Park');
INSERT INTO publisher (publisher_name) VALUES ('DV Giochi');
INSERT INTO publisher (publisher_name) VALUES ('Dwarfstar Games');
INSERT INTO publisher (publisher_name) VALUES ('Eurogames (game publisher)');
INSERT INTO publisher (publisher_name) VALUES ('Fantasy Flight Games');
INSERT INTO publisher (publisher_name) VALUES ('Fireside Games');
INSERT INTO publisher (publisher_name) VALUES ('Flying Buffalo');
INSERT INTO publisher (publisher_name) VALUES ('France Cartes');
INSERT INTO publisher (publisher_name) VALUES ('Funko');
INSERT INTO publisher (publisher_name) VALUES ('F.X. Schmid');
INSERT INTO publisher (publisher_name) VALUES ('Gale Force Nine');
INSERT INTO publisher (publisher_name) VALUES ('The Game Crafter');
INSERT INTO publisher (publisher_name) VALUES ('Game Designers Workshop');
INSERT INTO publisher (publisher_name) VALUES ('The Gamers');
INSERT INTO publisher (publisher_name) VALUES ('Games Workshop');
INSERT INTO publisher (publisher_name) VALUES ('Gamewright Games');
INSERT INTO publisher (publisher_name) VALUES ('Gibsons Games');
INSERT INTO publisher (publisher_name) VALUES ('Gigamic');
INSERT INTO publisher (publisher_name) VALUES ('GMT Games');
INSERT INTO publisher (publisher_name) VALUES ('Grenadier Models Inc.');
INSERT INTO publisher (publisher_name) VALUES ('Grey Ghost Press');
INSERT INTO publisher (publisher_name) VALUES ('Group SNE');
INSERT INTO publisher (publisher_name) VALUES ('Grow Jogos e Brinquedos');
INSERT INTO publisher (publisher_name) VALUES ('Guidon Games');
INSERT INTO publisher (publisher_name) VALUES ('Habermaaß');
INSERT INTO publisher (publisher_name) VALUES ('Hans im Glück');
INSERT INTO publisher (publisher_name) VALUES ('Hasbro');
INSERT INTO publisher (publisher_name) VALUES ('Hexagames');
INSERT INTO publisher (publisher_name) VALUES ('Hidden City Entertainment');
INSERT INTO publisher (publisher_name) VALUES ('Inside the Box Board Games');
INSERT INTO publisher (publisher_name) VALUES ('International Team');
INSERT INTO publisher (publisher_name) VALUES ('J. W. Spear & Sons');
INSERT INTO publisher (publisher_name) VALUES ('Steve Jackson Games');
INSERT INTO publisher (publisher_name) VALUES ('Jedko Games');
INSERT INTO publisher (publisher_name) VALUES ('Jeux Descartes');
INSERT INTO publisher (publisher_name) VALUES ('JKLM Games');
INSERT INTO publisher (publisher_name) VALUES ('Kenzer & Company');
INSERT INTO publisher (publisher_name) VALUES ('Kosmos (publisher)');
INSERT INTO publisher (publisher_name) VALUES ('Last Unicorn Games');
INSERT INTO publisher (publisher_name) VALUES ('Late for the Sky Production Company');
INSERT INTO publisher (publisher_name) VALUES ('Leder Games');
INSERT INTO publisher (publisher_name) VALUES ('Lemada');
INSERT INTO publisher (publisher_name) VALUES ('Lock n Load Publishing');
INSERT INTO publisher (publisher_name) VALUES ('Lookout Games');
INSERT INTO publisher (publisher_name) VALUES ('Looney Labs');
INSERT INTO publisher (publisher_name) VALUES ('Mantic Games');
INSERT INTO publisher (publisher_name) VALUES ('Mayfair Games');
INSERT INTO publisher (publisher_name) VALUES ('Merillian');
INSERT INTO publisher (publisher_name) VALUES ('Milton Bradley Company');
INSERT INTO publisher (publisher_name) VALUES ('Miro Company');
INSERT INTO publisher (publisher_name) VALUES ('Mongoose Publishing');
INSERT INTO publisher (publisher_name) VALUES ('Nexus Editrice');
INSERT INTO publisher (publisher_name) VALUES ('NIBCARD Games');
INSERT INTO publisher (publisher_name) VALUES ('North Star Games');
INSERT INTO publisher (publisher_name) VALUES ('Nürnberger-Spielkarten-Verlag');
INSERT INTO publisher (publisher_name) VALUES ('Operational Studies Group');
INSERT INTO publisher (publisher_name) VALUES ('Out of the Box Publishing');
INSERT INTO publisher (publisher_name) VALUES ('Outset Media');
INSERT INTO publisher (publisher_name) VALUES ('Pacesetter Ltd');
INSERT INTO publisher (publisher_name) VALUES ('Parker Brothers');
INSERT INTO publisher (publisher_name) VALUES ('Pirateer');
INSERT INTO publisher (publisher_name) VALUES ('Plaid Hat Games');
INSERT INTO publisher (publisher_name) VALUES ('Pressman Toy Corporation');
INSERT INTO publisher (publisher_name) VALUES ('Queen Games');
INSERT INTO publisher (publisher_name) VALUES ('RAFM Company');
INSERT INTO publisher (publisher_name) VALUES ('Ral Partha Enterprises');
INSERT INTO publisher (publisher_name) VALUES ('Ravensburger');
INSERT INTO publisher (publisher_name) VALUES ('Renegade Game Studios');
INSERT INTO publisher (publisher_name) VALUES ('Rio Grande Games');
INSERT INTO publisher (publisher_name) VALUES ('Roxley');
INSERT INTO publisher (publisher_name) VALUES ('Schmidt Spiele');
INSERT INTO publisher (publisher_name) VALUES ('Selchow and Righter');
INSERT INTO publisher (publisher_name) VALUES ('Simulations Publications, Inc.');
INSERT INTO publisher (publisher_name) VALUES ('Task Force Games');
INSERT INTO publisher (publisher_name) VALUES ('TerrorBull Games');
INSERT INTO publisher (publisher_name) VALUES ('TESA Collective');
INSERT INTO publisher (publisher_name) VALUES ('Tilsit Éditions');
INSERT INTO publisher (publisher_name) VALUES ('Tower Press');
INSERT INTO publisher (publisher_name) VALUES ('Trefl');
INSERT INTO publisher (publisher_name) VALUES ('Tuonela Productions');
INSERT INTO publisher (publisher_name) VALUES ('Überplay');
INSERT INTO publisher (publisher_name) VALUES ('Waddingtons');
INSERT INTO publisher (publisher_name) VALUES ('John Wallis (publisher)');
INSERT INTO publisher (publisher_name) VALUES ('West End Games');
INSERT INTO publisher (publisher_name) VALUES ('Wild Card Games');
INSERT INTO publisher (publisher_name) VALUES ('Wizards of the Coast');
INSERT INTO publisher (publisher_name) VALUES ('Wyrd (company)');
INSERT INTO publisher (publisher_name) VALUES ('Yaquinto Publications');
INSERT INTO publisher (publisher_name) VALUES ('Z-Man Games');
INSERT INTO publisher (publisher_name) VALUES ('Zoch Verlag');